BBBB BBBB
XXXXXXXXX XXXXX
XXXXXX
XXXXXX
    XXXXXXX gettext(u'Simple Template') XXXXXXXX
XXXXXXX
XXXXXX
    XXXXX XXXXXXXXBBB BBBBBBBBBBBBBBX XXXXXXXXXXXXXX
        BBBBBBBBBB
        XXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXXX XXXXXXXXXX BB BBBBBBBBBBBBB BB BBBBXXXXXXXXBBBBBXXXXXXXXXXXXXXXXX
            XXXXXXX XXXXXXXXXX BB BBBBBBBBBBBBB BB BBBBXXXXXXXXBBBBBXXXXXXXXXXXXXXXXX
            XXXX XXX XXXX XXXXXXXXX XX XXXXXX XXX
        XXXXXXXXX
    XXXXXXX
    XXXX gettext(u'Hello, World!') XXXXX
    XXX gettext(u'This is a simple Django template.') XXXX
XXXXXXX
XXXXXXX
